twitter_dbt:
  outputs:
    dev:
      dataset: twitter_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "secrets/dbt-service-keyfile.json"
      location: US
      method: service-account
      priority: interactive
      project: "twitter-project-328515"
      threads: 4
      type: bigquery
  target: dev
